version: "3.9"

services:
  api:
    profiles: ["gpu"]
    build:
      context: ../../../Downloads
      dockerfile: backend/Dockerfile.gpu
    environment:
      NVIDIA_VISIBLE_DEVICES: all
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
